version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miftah87
      POSTGRES_DB: dmy_users
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  go-crud:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
