# Stage 1: Build binary
FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o app .

# Stage 2: Minimal runtime
FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/app .

# Tidak perlu salin .env — akan dipasang saat runtime lewat docker-compose
EXPOSE 8080

CMD ["./app"]
