# name: Docker Auto-Deploy

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Deploy via SSH
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: ${{ secrets.SERVER_PORT }} # opsional jika bukan 22
#           script: |
#             cd ${{ secrets.DEPLOY_PATH }}

#             # Reset & pull source
#             git fetch --all
#             git reset --hard origin/main
#             git pull origin main

#             # Build & deploy dengan Docker
#             docker build -t go-crud .

#             docker stop go-crud || true
#             docker rm go-crud || true

#             docker run -d \
#               --name go-crud \
#               -p 8080:8080 \
#               --restart unless-stopped \
#               go-crud


name: Deploy ke Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        uses: railwayapp/cli-action@master

      - name: Deploy ke Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
