name: Docker Auto-Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main
            docker build -t go-crud .
            docker stop go-crud || true
            docker rm go-crud || true
            docker run -d --name go-crud -p 8080:8080 --restart unless-stopped go-crud
            
            # Jika pakai docker-compose:
            # docker-compose down
            # docker-compose up -d --build
